### ISSUE TITLE
Buildkite CI broken on staging branch

### ISSUE THREAD

**Issue by tsj5** [CliMA/CalibrateEmulateSample.jl#125]
**Issue:**
[CI](https://buildkite.com/clima/calibrateemulatesample-ci/builds/50#8fda231f-52ab-47d7-89a6-6c0f7ed7e738) for PR #120 (`staging` branch) fails in the `init_project_env` setup stage. The error happens in `Pkg.instantiate()`, before Python dependencies are added:

```
Added registry `General` to `/central/scratch/climaci/calibrateemulatesample-ci/50/depot/cpu/registries/General`
--
  | Cloning git-repo `https://github.com/CliMA/EnsembleKalmanProcesses.jl`
  | ERROR: TypeError: in typeassert, expected VersionNumber, got a value of type Pkg.Types.VersionSpec
  | Stacktrace:
  | [1] load_urls(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:510
  | [2] #download_source#54 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:686 [inlined]
  | [3] download_source at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:685 [inlined]
  | [4] instantiate(::Pkg.Types.Context; manifest::Nothing, update_registry::Bool, verbose::Bool, platform::Pkg.BinaryPlatforms.Linux, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:875
  | [5] #instantiate#169 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:791 [inlined]
  | [6] top-level scope at none:1
  | 🚨 Error: The command exited with status 1
```

**Diagnosis:**
Googling the error message suggests this is caused by using a `Manifest.toml` from an incompatible version of Julia (differing minor version number): [ref 1](https://discourse.julialang.org/t/incompatible-changes-in-pkg/51326/5); [ref 2](https://github.com/tlienart/Franklin.jl/issues/868). 

This was introduced in 7f038a471fd55d61ddd9e9e880ae4203303de68c, which updates `Manifest.toml` to package versions apparently consistent with Julia 1.6.2, while the buildkite config is still using 1.5.4. 

**Proposed fix:**
Full reproducibility is, implicitly, a requirement of the CES project, so `Manifest.toml` must remain [tracked in the repo](https://discourse.julialang.org/t/does-manifest-toml-belong-in-the-repository/12029). This means the project must standardize on one minor version of Julia. I'm ignorant of whether there's a CliMA-wide policy on this, but the [current long-term support release](https://discourse.julialang.org/t/julia-v1-7-0-has-been-released-and-v1-6-is-now-lts/72336) is 1.6.5, which would imply updating buildkite and all tests to 1.6.

**Comment by odunbar** [comment]
Hi jake, I don't suppose you can shed any light on these issues?

**Comment by tsj5** [comment]
Thanks for the approval, @jakebolewski and @odunbar -- apologies things are still broken! One of you will need to check which environment modules are available in order to fix things:

The new CI [error](https://buildkite.com/clima/calibrateemulatesample-ci/builds/51#a6ce6880-ef9d-4af9-b854-b3d41ff939fd) the current PR encounters is that the julia executable can't be found (line 103), due to the fact (line 5) that it's
```
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'julia/1.6.5'
```
My understanding is that buildkite jobs are running on your own cluster (not containerized), so I'd need one of you to look up the available environment modules on that machine in order to fix this. 1.6.5 was only released a month ago, so it may be premature to expect it to be available.

I'm confused by the fact that Oceananigans.jl [specifies 1.6.5](https://github.com/CliMA/Oceananigans.jl/blob/main/.buildkite/pipeline.yml) in its buildkite setup, yet the CI on `main` is passing. I'm guessing it runs on a different machine, due to GPU use?

**Comment by tsj5** [comment]
Thanks for the approval, @jakebolewski and @odunbar -- apologies things are still broken! One of you will need to check which environment modules are available in order to fix things:

The new CI [error](https://buildkite.com/clima/calibrateemulatesample-ci/builds/51#a6ce6880-ef9d-4af9-b854-b3d41ff939fd) the current PR encounters is that the julia executable can't be found (line 103), due to the fact (line 5) that it's
```
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'julia/1.6.5'
```
My understanding is that buildkite jobs are running on your own cluster (not containerized), so I'd need one of you to look up the available environment modules on that machine in order to fix this. 1.6.5 was only released a month ago, so it may be premature to expect it to be available.

I'm confused by the fact that Oceananigans.jl [specifies 1.6.5](https://github.com/CliMA/Oceananigans.jl/blob/main/.buildkite/pipeline.yml) in its buildkite setup, yet the CI on `main` is passing. I'm guessing it runs on a different machine, due to GPU use?

**Comment by jakebolewski** [comment]
we don't currently have a 1.6.5 build on the cluster (we load the specific julia version through env modules as you noted above).  I will put in a ticket for that but a quick fix is to use one we have available:

```
------------------------------- /software/Modules/modulefiles/developement --------------------------------
julia/1.0.1     julia/1.1.0     julia/1.3.1     julia/1.4.2     julia/1.5.2     julia/1.6.2
julia/1.0.3     julia/1.2.0     julia/1.4.0     julia/1.5.0     julia/1.5.4     julia/1.7.0
julia/1.0.5-lts julia/1.3.0     julia/1.4.1     julia/1.5.1     julia/1.6.0     julia/1.7.1
```

**Comment by tsj5** [comment]
Closing, as this has been fixed by PR #120.
